# Generated by Django 3.2.9 on 2022-12-22 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='abi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='supers.abilities'),
        ),
    ]
