# Generated by Django 3.2.9 on 2022-12-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0002_character_abi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='abi',
        ),
        migrations.AddField(
            model_name='character',
            name='abilities',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Abilities',
        ),
    ]
