# Generated by Django 3.2.9 on 2022-12-22 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0003_auto_20221222_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='abilities',
        ),
    ]
